apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poll-app
  template:
    metadata:
      labels:
        app: poll-app
    spec:
      containers:
      - name: poll-app
        image: manokac55/django-poll-app:latest
        ports:
        - containerPort: 8000
      strategy:
        canary:
          steps:
          - setWeight: 20
            pause: {}
          - setWeight: 40
            pause:
              duration: 10
          - setWeight: 60
            pause:
              duration: 10
          - setWeight: 80
            pause:
              duration: 10
---
apiVersion: v1
kind: Service
metadata:
  name: django-poll-app
spec:
  ports:
  - port: 3000
    targetPort: 8000
  selector:
    app: poll-app
  type: LoadBalancer
